name: Testes Mobile no BrowserStack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: browser

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar dependências
      run: npm install

    - name: Fazer upload do APK para o BrowserStack
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        response=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
          -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
          -F "file=@app/app-demo.apk")
        app_id=$(echo $response | jq -r '.app_url')
        echo "APP_ID=$app_id" >> $GITHUB_ENV

    - name: Rodar os testes no BrowserStack
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: npx wdio config/wdio.conf.js --spec ./tests/home/home.test.js
